### PR TITLE
Tims

### PR DESCRIPTION
**Pull request by othtim**
some british focus tree localization and made continuing boxer war actually work

### CODE REVIEW

**Comment by othtim** [comment]
pls ignore my previous opened-then-closed pull request, that was done in error

**Comment by mikegent01** [comment]
If you want to rejoin the mod you should prob join the discord https://discord.gg/gFBRzhxCyc

**Comment by othtim** [comment]
i'm in the discord, but i dont have permission to speak in border control, so i cannot join.

**Comment by mikegent01** [comment]
what is your username

**Comment by othtim** [comment]
othtim

**Pull request merged**
